language: python
python:
  - 2.7
  - 3.4
install: "pip install Django==$DJANGO_VERSION --use-mirrors"
script: loginas/tests/manage.py test --verbosity=2 tests
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
